// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
var attributes = {
    podcastURL: unescape('http://ccmixter.org/media/api/query?score=400%26sinceu=1163449268%26limit=25%26tags=remix+editorial_pick%26rand=1%26format=rss'),
    refreshInterval: '60'
};