// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { foregroundStyle: 'white', onclick: 'showBack', backgroundStyle: 'black', frontID: 'front' });
    CreateGlassButton('done', { onclick: 'showFront', rightImageWidth: 1, leftImageWidth: 1, text: 'Done' });
    CreateText('podcast_name', { text: unescape('ccmixter.org editor%27s picks') });
    CreateText('episode_description', { text: 'Episode Description' });
    CreateText('episode_date', { text: 'Episode Date' });
    CreateGlassButton('subscribe_button', { text: 'Subscribe to Podcast', onclick: 'subscribe' });
    CreateButton('episode_name', { rightImageWidth: 16, leftImageWidth: 8, text: 'Track Name' });
    CreateGlassButton('trackbutton', { text: 'trackbutton_label', onclick: 'onTrackButtonClick' });
    CreateText('track_link', { text: 'Text' });
}
window.addEventListener('load', setupParts, false);
